todosite/authentication/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    home,
    get_sign_up,
    sign_sucessfull,
    get_login,
    validate_login,
    set_logout,
    login_fail,
    passwd_recovery,
    set_change_in_password,
)

app_name = "authentication"

urlpatterns = [
    path("sign-up/", get_sign_up, name="sign-up"),
    path("login/", get_login, name="login"),
    path("login-failed/", login_fail, name="login-failed"),
    path("logout/", set_logout, name="logout"),
    path("login-validation/", validate_login, name="login_validation"),
    path("sign-up-success/", sign_sucessfull, name="sign_successfull"),
    path("passwd-recovery/", passwd_recovery, name="passwd-recovery"),
    path(
        "set-change-password/",
        set_change_in_password,
        name="set-change-password",
    ),
]

todosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todosite.base.urls"), name="base"),
    path("auth/", include("todosite.authentication.urls"), name="login"),
    path(
        "profile/",
        include("todosite.user_profile.urls"),
        name="user-profile",
    ),
]

todosite/user_profile/urls.py
from django.urls import path, include
from .views import get_profile, delete_account, change_username


app_name = "user_profile"

urlpatterns = [
    path("", get_profile, name="profile-index"),
    path("delete-account/<str:username>/", delete_account, name="delete-account"),
    path("change-username/<int:pk>/", change_username, name="change-username"),
]

todosite/user_profile/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    birthday = models.DateField()

    def __repr__(self):
        return user.username

todosite/user_profile/forms.py
from django import forms


class ChangeUserName(forms.Form):
    new_name = forms.CharField(max_length=15)

todosite/user_profile/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


from ..base.models import Task, Issue
from .forms import ChangeUserName


@login_required(login_url="../../auth/login/")
def get_profile(request: HttpRequest) -> HttpResponse:
    """
    loads the user profile

    Args:
        - request (HttpRequest)

    return: HttpResponse
    """
    user = request.user
    tasks = Task.objects.filter(user=user)

    buffer = list()
    issues = list(Issue.objects.all())
    issue = list(filter(lambda x: x.task in tasks, issues))

    context = {
        "pk": user.pk,
        "username": user.username,
        "number_tasks": len(tasks),
        "number_issues": len(issue),
    }
    return render(request, "user_profile/profile.html", context)


@login_required
def delete_account(request: HttpRequest, username: str) -> HttpResponse:
    """
    Insert some doc here
    """
    name = User.objects.filter(username=username)
    name[0].delete()
    return HttpResponseRedirect("../../../auth/login/")


def change_username(request: HttpRequest, pk: int) -> HttpResponse:
    """Modify user's 'username"""
    message = None

    if request.method == "POST":
        user = User.objects.filter(pk=pk)[0]
        form = ChangeUserName(request.POST)
        new_name = request.POST.get("new_name")

        if len(list(User.objects.filter(username=new_name))) == 0:
            user.username = new_name
            user.save()
            return HttpResponseRedirect("/../profile/")
        else:
            message = "Este username já está sendo utilizado."

    else:
        form = ChangeUserName()

    context = {
        "pk": request.user.pk,
        "username": request.user.username,
        "form": form,
        "message": message,
    }

    return render(request, "user_profile/change_username.html", context=context)

todosite/user_profile/templates/user_profile/base_profile.html
{% extends 'base/base.html' %}

{% block title %}Todo App - Profile{% endblock %}
{% block description %}"Todo list - Profile"{% endblock %}
<!-- Image and text -->
{% block exit %}
    <a class="btn btn-danger" href={% url 'authentication:logout' %} role="button">  Sair</a>
{% endblock %}
{% block nav_title %}Perfil{% endblock %}

{% block body %}
    <br>
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <h5 class="card-header">
                    {% block username_field %}
                    {% endblock %}
                </h5>
                <div class="card-body">
                    <p class="card-text">
                        Tasks registradas: {{ number_tasks }}
                    </p>
                </div>
                <div class="card-footer">
                    Issues regisradas: {{ number_issues }}
                </div>
            </div>
        </div>
    </div>
    </div>
    <br><br>
    <p style="text-align:center;">
        <a class="btn btn-danger" href={% url 'user_profile:delete-account' username %} role="button">  Deletar conta</a>
    </p>
{% endblock %}

todosite/user_profile/templates/user_profile/change_username.html
{% extends 'user_profile/base_profile.html' %}
{% block username_field %}

{% if message is not None %}
        <div class="alert alert-danger" role="alert">
              {{ message }}
        </div>
{% endif %}

<form class="form-group" action={% url 'user_profile:change-username' pk %} method="post">
        {% csrf_token %}
        {{ form.new_name }}
        <button type="submit" class="btn btn-primary">Mudar</button>
</form>
{% endblock %}

todosite/user_profile/templates/user_profile/profile.html
{% extends 'user_profile/base_profile.html' %}
{% block username_field %}
    Username: {{ username }}
    <br>
    <a href={% url 'user_profile:change-username' pk %}>
{% endblock %}