todosite/authentication/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    home,
    get_sign_up,
    sign_sucessfull,
    get_login,
    validate_login,
    set_logout,
    login_fail,
    passwd_recovery,
    set_change_in_password,
)

app_name = "authentication"

urlpatterns = [
    path("sign-up/", get_sign_up, name="sign-up"),
    path("login/", get_login, name="login"),
    path("login-failed/", login_fail, name="login-failed"),
    path("logout/", set_logout, name="logout"),
    path("login-validation/", validate_login, name="login_validation"),
    path("sign-up-success/", sign_sucessfull, name="sign_successfull"),
    path("passwd-recovery/", passwd_recovery, name="passwd-recovery"),
    path(
        "set-change-password/",
        set_change_in_password,
        name="set-change-password",
    ),
]

todosite/base/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    home,
    new_task,
    new_issue,
    delete_task,
    change_status_of_task,
    change_status_of_issue,
    delete_issue,
)

app_name = "base"

urlpatterns = [
    path("", home, name="home"),
    path("new-task/", new_task, name="new-task"),
    path("new-issue/<int:pk>/", new_issue, name="new-issue"),
    path("delete-task/<int:pk>", delete_task, name="delete"),
    path(
        "change-status/<int:pk>/",
        change_status_of_task,
        name="change_status",
    ),
    path(
        "change-status-issue/<int:pk>/",
        change_status_of_issue,
        name="change_status_of_issue",
    ),
    path("delete-task/<int:pk>/", delete_issue, name="delete_issue"),
]

todosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todosite.base.urls"), name="base"),
    path("auth/", include("todosite.authentication.urls"), name="login"),
    path(
        "profile/",
        include("todosite.user_profile.urls"),
        name="user-profile",
    ),
]

todosite/user_profile/urls.py
from django.urls import path, include
from .views import get_profile, delete_account, change_username


app_name = "user_profile"

urlpatterns = [
    path("", get_profile, name="profile-index"),
    path("delete-account/<str:username>/", delete_account, name="delete-account"),
    path("change-username/<int:pk>/", change_username, name="change-username"),
]

todosite/base/models.py
from django.db import models
from django.contrib.auth.models import User

status_choices = [("Done", "Done"), ("Pending", "Pending")]


class Task(models.Model):
    task_name = models.CharField(max_length=30)
    description = models.TextField()
    pub_date = models.DateField("date published", auto_now_add=True)
    status = models.CharField(max_length=120, choices=status_choices, default="Pending")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.task_name

    class Meta:
        ordering = ["-pub_date"]


class Issue(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    issue_description = models.TextField()
    pub_date = models.DateField("date published", auto_now_add=True)
    status = models.CharField(max_length=120, choices=status_choices, default="Pending")

    def __str__(self):
        return self.issue_description

    class Meta:
        ordering = ["-pub_date"]

todosite/base/forms.py
from django import forms
from .models import status_choices
from django.contrib.auth.models import User


class SignUpForm(forms.Form):
    name = forms.CharField(max_length=100)
    passwd = forms.CharField(widget=forms.PasswordInput)


class NewTaskForm(forms.Form):
    task_name = forms.CharField(max_length=30)
    description = forms.CharField(max_length=120)
    pub_date = forms.DateField()
    status = forms.ChoiceField(choices=status_choices)


class NewIssueForm(forms.Form):
    description = forms.CharField(max_length=120)
    pub_date = forms.DateField()
    status = forms.ChoiceField(choices=status_choices)

todosite/base/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse
from django.shortcuts import render


from .models import Task, Issue
from .forms import SignUpForm, NewTaskForm, NewIssueForm
from .facade import create_task, create_issue, get_task_by_name


@login_required(login_url="/auth/login/")
def home(request: HttpRequest) -> HttpResponse:
    """
    Application homepage view

    Args:
        - request (HttpRequest): Web request for homepage

    Return: (HttpResponse) Web Response that renders the HomePage template
    """
    context = {
        "username": request.user.username,
        "tasks": Task.objects.all(),
        "issues": Issue.objects.all(),
    }
    return render(request, "base/index.html", context)


def new_task(request: HttpRequest) -> HttpResponse:
    """
    Create new task card for user

    Args:
        - request: HttpRequest

    return: HttpResponse
    """
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        task_name = request.POST.get("task_name")
        description = request.POST.get("description")
        pub_date = request.POST.get("pub_date")
        status = request.POST.get("status")
        user = request.user
        create_task(
            task_name=task_name,
            description=description,
            pub_date=pub_date,
            status=status,
            user=user,
        )
        return HttpResponseRedirect("/")
    else:
        form = NewTaskForm()

    context = {
        "username": request.user.username,
        "tasks": Task.objects.all(),
        "issues": Issue.objects.all(),
        "form": form,
    }
    return render(request, "base/new_task.html", context)


def new_issue(request: HttpRequest, pk: int) -> HttpResponse:
    """
    Create a new Issue for some task

    Args:
        - request (HttpRequest)
        - pk (int): Parent task id for the created issue

    return: HttpResponse
    """
    task = Task.objects.filter(pk=pk)[0]
    if request.method == "POST":
        form = NewIssueForm(request.POST)
        description = request.POST.get("description")
        pub_date = request.POST.get("pub_date")
        status = request.POST.get("status")

        if task is not None:
            create_issue(
                issue_description=description,
                pub_date=pub_date,
                status=status,
                task=task,
            )
        return HttpResponseRedirect("/")
    else:
        form = NewIssueForm()

    context = {
        "username": request.user.username,
        "tasks": Task.objects.all(),
        "issues": Issue.objects.all(),
        "form": form,
        "pk": task.pk,
    }
    return render(request, "base/new_issue.html", context)


def delete_task(request: HttpRequest, pk: int) -> HttpResponse:
    """
    Remove task

    Args:
        - request (HttpRequest)
        - pk (int): task id

    return HttpResponse
    """
    task = Task.objects.filter(pk=pk).delete()
    return HttpResponseRedirect("/")


def change_status_of_task(request, pk: int) -> HttpResponse:
    """
    Change Task status

    Args:
        - request (HttpRequest)
        - pk (int): task id to be apllied the change

    Return: HttpResponse
    """
    choices = ("Pending", "Done")
    task = Task.objects.filter(pk=pk)[0]
    l = list(map(lambda x: x == task.status, choices))
    task.status = choices[l.index(False)]
    task.save()
    return HttpResponseRedirect("/")


def change_status_of_issue(request: HttpRequest, pk: int) -> HttpResponse:
    """
    Change the issue current status

    Args:
        - request (HttpRequest)
        - pk: issue id

    Return: HttpResponse
    """
    choices = ("Pending", "Done")
    issue = Issue.objects.filter(pk=pk)[0]
    l = list(map(lambda x: x == issue.status, choices))
    issue.status = choices[l.index(False)]
    issue.save()
    return HttpResponseRedirect("/")


def delete_issue(request: HttpRequest, pk: int):
    """
    Delets a issue for a given pk
    """
    issue = Issue.objects.filter(pk=pk)[0]
    issue.delete()
    return HttpResponseRedirect("/")

todosite/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>

    <meta name="description" content={% block  description %}{% endblock %}>
    <meta name="author" content="Victor Pereira">

    <link rel="icon" type="image/png" href="/static/img/icon.png"/>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/scripts.js"></script>

  </head>
  <body>
      <nav class="navbar navbar-dark bg-dark">
          <a class="navbar-brand" href={% url  'base:home' %}>
              <img src="/static/img/icon.png" alt="Logo da aplicação" width="50" height="50">
              {% block nav_title %}{% endblock %}
          </a>
          <p align="right">
              <a class="navbar-brand" href={% url 'user_profile:profile-index' %}>{{ username }}  </a>
              {% block exit %}{% endblock %}
          </p>
      </nav>
      {% block body %}{% endblock %}
  </body>
  {% include 'base/footer.html' %}
</html>

todosite/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4">
    <div class="rights pb-4">
        <div class="container">
            <div class="row">
                <div class="col" align="center">
                    Victor Pereira
                </div>
            </div>
        </div>
    </div>

todosite/base/templates/base/index.html
{% extends "base/base.html" %}
{% block title %}Todo App - Toy Application{% endblock %}
{% block description %}"Todo list"{% endblock %}
<!-- Image and text -->
{% block exit %}
    <a class="btn btn-danger" href={% url 'authentication:logout' %} role="button">  Sair</a>
{% endblock %}
{% block nav_title %}Todo App - Toy application{% endblock %}

{% block body %}
        <br>
        <p align="center"><a href={% url 'base:new-task' %}>
            <img src="/static/img/plus.png" alt="icone de lixeira" width="60" height="60"></a>
        </p>
        <div class="container-fluid">
        {% block new %}{% endblock new %}
            {% for task in tasks %}
                {% if task.user.username == username %}
                    <br>
                    <div class="card" style="width: 30rem; margin: 0 auto;border-color:#0a106e;">
                        <div class="card-body">
                            <h5 align="center" class="card-title">{{ task.task_name }}
                                {% if task.status == "Done" %}
                                    &#10004
                                {% else %}
                                    &#10005;
                                {% endif %}

                                <a href={% url 'base:delete' task.pk %}>
                                    <img src="/static/img/trash.png" alt="icone de liceira" width="20" height="20">
                                </a>
                                <a href={% url 'base:change_status' task.pk %}>
                                    <img src="/static/img/reverse.png" alt="trocar status" width="20" height="20">
                                </a>
                            </h5>
                            <h5>
                                Descrição:
                            </h5>
                            <p class="card-text">{{ task.description }}</p>
                            <br>
                            <p><h6 class="card-subtitle mb-2 text-muted">Issues</h6></p>
                            {% for issue in issues %}
                                {% if issue.task ==  task %}
                                    <p>
                                        <a href="#" class="card-link">* {{ issue.issue_description }}</a>

                                        {% if issue.status == "Done" %}
                                        &#10004
                                        {% else %}
                                        &#10005;
                                        {% endif %}

                                        <a href={% url 'base:change_status_of_issue' issue.pk %}>
                                            <img src="/static/img/reverse.png" alt="icone de mudança de status" width="20" height="20">
                                        </a>
                                        <a href={% url 'base:delete_issue' issue.pk %}>
                                            <img src="/static/img/trash.png" alt="icone de lixeira" width="20" height="20">
                                        </a>
                                    </p>
                                {% endif %}
                            {% endfor %}
                            {% block new_issue %}{% endblock new_issue %}
                        </div>
                        <p align="center">
                            <a href={% url 'base:new-issue' task.pk %}>
                                <img src="/static/img/plus.png" alt="Adicionar issue" width="25" height="25">
                            </a>
                        </p>
                    </div>
                {% endif %}
            {% endfor %}

        </div>

  {% endblock %}

todosite/base/templates/base/login.html
{% extends "base/base.html" %}
{% block title %}Todo App - Login{% endblock %}
{% block nav_title %}Todo App - Login{% endblock %}
{% block body %}
    <form class="form-group" action="/login-validation/" method="post">
        {% csrf_token %}
        <br>
        {% if message %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endif %}
        <div class="form-group" align="center">
            <label for="exampleInputEmail1" class="form-control">Usuário</label>
            {{ form.name }}
            <br>
        </div>
        <div class="form-group" align="center">
            <label for="inputPassword" class="form-control">Senha</label>
            {{ form.passwd }}
            <br>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Entrar</button>
            <p>
                <a href="/sign-up/">Não tem uma conta? Cadastre-se</a>
            </p>
        </div>
    </form>
{% endblock %}

todosite/base/templates/base/new_issue.html
{% extends 'base/index.html' %}
{% block new_issue %}
    {% if task.pk == pk %}
        <form action={% url 'base:new-issue'  task.pk %} method="post">
            {% csrf_token %}
            <p class="card-text"> Descrição {{ form.description }}</p>
            <p class="card-text"> Status <br>{{ form.status }}</p>

            <input type="submit" value="OK">
        </form>
    {% endif %}
{% endblock %}

todosite/base/templates/base/new_task.html
{% extends 'base/index.html' %}
{% block new %}
    <br>
    <div class="card" style="width: 30rem; margin: 0 auto;">
        <form action="/new-task/" method="post">
            {% csrf_token %}
        <div class="card-body">
            <h5 class="card-title">Título <br> {{ form.task_name }}</h5>
            <p class="card-text"> Descrição <br> {{ form.description }}</p>
            <p class="card-text">Status <br>{{ form.status }}</p>

            <input type="submit" value="OK">
        </form>
        </div>
    </div>
{% endblock new %}

todosite/base/templates/base/sign.html
{% extends "base/base.html" %}
{% block title %}Todo App - Cadastrar{% endblock %}
{% block nav_title %}Todo App - Cadastrar{% endblock %}
{% block body %}
    <form class="form-group" action="/sign-up-success/" method="post">
        {% csrf_token %}
        <br>
        {% if message %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endif %}
        <div class="form-group" align="center">
            <label for="exampleInputEmail1" class="form-control">Usuário</label>
            {{ form.name }}
            <br>
        </div>
        <div class="form-group" align="center">
            <label for="inputPassword" class="form-control">Senha</label>
            {{ form.passwd }}
            <br>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
    </form>
{% endblock %}