todosite/authentication/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    home,
    get_sign_up,
    sign_sucessfull,
    get_login,
    validate_login,
    set_logout,
    login_fail,
    passwd_recovery,
    set_change_in_password,
)

app_name = "authentication"

urlpatterns = [
    path("sign-up/", get_sign_up, name="sign-up"),
    path("login/", get_login, name="login"),
    path("login-failed/", login_fail, name="login-failed"),
    path("logout/", set_logout, name="logout"),
    path("login-validation/", validate_login, name="login_validation"),
    path("sign-up-success/", sign_sucessfull, name="sign_successfull"),
    path("passwd-recovery/", passwd_recovery, name="passwd-recovery"),
    path(
        "set-change-password/",
        set_change_in_password,
        name="set-change-password",
    ),
]

todosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todosite.base.urls"), name="base"),
    path("auth/", include("todosite.authentication.urls"), name="login"),
    path(
        "profile/",
        include("todosite.user_profile.urls"),
        name="user-profile",
    ),
]

todosite/authentication/models.py
from django.db import models

# Create your models here.

todosite/authentication/forms.py
from django import forms
from django.contrib.auth.models import User


class SignUpForm(forms.Form):
    name = forms.CharField(max_length=100)
    passwd = forms.CharField(widget=forms.PasswordInput)


class RecoveryPasswordForm(forms.Form):
    username = forms.CharField(max_length=100)
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

todosite/authentication/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.db.utils import IntegrityError
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse


from .forms import SignUpForm, RecoveryPasswordForm
from .facade import user_existis, remove_user
from ..base.views import home


def get_sign_up(request: HttpRequest, *args: list) -> HttpResponse:
    """
    Sign Up page view, responsible for renders the sign up form

    Args:
        - request (HttpRequest): Web request for the sign uo form page

    Return: (HttpResponse) Web Response that renders the sign up template
    """
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect("/auth/sign-up-success/")

    else:
        form = SignUpForm()
    return render(
        request,
        "authentication/sign.html",
        {
            "form": form,
            "message": lambda: args[0] if len(args) > 0 else None,
        },
    )


def sign_up_fail(request: HttpRequest) -> HttpResponse:
    """
    render sign up form with an warning message

    Args:
        - request (HttpRequest)

    Return: HttpResponse
    """
    return get_sign_up(request, "Este username já está sendo utilizado")


def sign_sucessfull(request: HttpRequest) -> HttpResponse:
    """
    User's creation view, called after sign up form submission

    Args:
        - request (HttpRequest)

    Return: HttpResponse
    """

    username = request.POST.get("name")
    password = make_password(request.POST.get("passwd"))

    try:
        User.objects.create(username=username, password=password)
        return home(request)
    except IntegrityError:
        return sign_up_fail(request)


def get_login(request: HttpRequest, *args: list) -> HttpResponse:
    """
    Login page view, responsible for renders the login form

    Args:
    - request (HttpRequest): Web request for the login page

    - Optional Arguments:
    - message: message displayed if the previous login failed
    - default value: None

    Return: (HttpResponse) Response that renders the login template
    """
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.isValid():
            return HttpResponseRedirect("/auth/login-validation/")
    else:
        form = SignUpForm()

    return render(
        request,
        "authentication/login.html",
        {
            "form": form,
            "message": lambda: args[0] if len(args) > 0 else None,
        },
    )


def login_fail(request: HttpRequest) -> HttpResponse:
    """
    calls get_login view with an login failed warning message

    Args:

        - request (HttpRequest)

    Return: HttpResponse
    """
    return get_login(request, "O login falhou, por favor tente novamente")


def validate_login(request: HttpRequest) -> HttpResponseRedirect:
    """
    view responsible for validate the user authentication credentials.

    Args:
        - request (HttpRequest)

    Return: (HttpResponse)
    """
    anonymous_user = authenticate(
        request=request,
        username=request.POST.get("name"),
        password=request.POST.get("passwd"),
    )
    if anonymous_user is not None:
        user = User.objects.filter(password=anonymous_user.password)[0]
        login(request, user)
        return HttpResponseRedirect("/")
    return HttpResponseRedirect("/auth/login-failed/")


def set_logout(request: HttpRequest) -> HttpResponseRedirect:
    """
    realizes the logout of plataform

    Args:
        - request (HttpRequest)

    Return: HttpResponseRedirect
    """
    logout(request)
    return HttpResponseRedirect("/auth/login/")


def passwd_recovery(request: HttpRequest) -> HttpResponse:
    """
    Shows the password recovery FOrm

    Args:
    Return:
    """
    if request.method == "POST":
        form = RecoveryPasswordForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect("/auth/set-change-password")
    else:
        form = RecoveryPasswordForm()

    return render(
        request,
        "authentication/recovery_password.html",
        context={"form": RecoveryPasswordForm()},
    )


def set_change_in_password(request: HttpRequest) -> HttpResponse:
    """"""
    username = request.POST.get("username")
    password = request.POST.get("new_password")
    confirm_password = request.POST.get("confirm_password")

    if password == confirm_password:
        all_users = list(User.objects.all())
        users = [user.username == username for user in all_users]
        user = all_users[users.index(True)]
        user.password = make_password(request.POST.get("new_password"))
        user.save()
        return HttpResponseRedirect("/auth/login/")

    context = {
        "form": RecoveryPasswordForm(),
        "message": "Nova Senha e Confirmação não coincidem!",
    }
    return render(request, "authentication/recovery_password.html", context=context)

todosite/authentication/templates/authentication/login.html
{% extends "base/base.html" %}
{% block title %}Todo App - Login{% endblock %}
{% block nav_title %}Todo App - Login{% endblock %}
{% block body %}
<br><br>
    <div class="card" style="width: 15rem; margin: 0 auto; border-width:2px; border-color:#0a106e;">
        <form class="form-group" action="/auth/login-validation/" method="post">
            {% csrf_token %}
            <br>
            {% if message %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endif %}
            <h5 align="center" class="card-title">Faça o seu Login</h5><br>
            <div class="form-group" align="center">
                <label for="exampleInputEmail1" class="form-control" style= "width: 13rem;border-color:black;">Usuário</label>
                {{ form.name }}
                <br>
            </div>
            <div class="form-group" align="center">
                <label for="inputPassword" class="form-control" style="width:13rem;border-color:black;">Senha</label>
                {{ form.passwd }}
                <br>
            </div>
            <br>
            <div class="text-center">
                <button type="submit" class="btn btn-primary" >Entrar</button>
                <br>
                <p style="margin:left;">
                    <a href={% url 'authentication:passwd-recovery' %}>Esqueci minha senha</a>
                    <br>
                </p>

                <a class="btn btn-secondary" href={% url 'authentication:sign-up'%} role="button">
                    Criar nova conta
                </a>
            </div>
        </form>
    </div>
{% endblock %}

todosite/authentication/templates/authentication/recovery_password.html
{% extends "base/base.html" %}
{% block title %}Todo App - Mudança de Senha{% endblock %}
{% block nav_title %}Todo App - Mudar Senha{% endblock %}
{% block body %}
<br><br>
    <div class="card" style="width: 20rem; margin: 0 auto; border-width:2px; border-color:#0a106e;">
        <form class="form-group" action={% url 'authentication:set-change-password' %} method="post">
            {% csrf_token %}
            <br>
            {% if message %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endif %}
            <h5 align="center" class="card-title">Mudança de Senha</h5><br>
            <div class="form-group" align="center">
                <label for="exampleInputEmail1" class="form-control" style= "width: 18rem; border-color:black;">Usuário<label>
                <br>
                {{ form.username }}
            </div>
            <br><br>

            <div class="form-group" align="center">
                <label for="exampleInputEmail1" class="form-control" style= "width: 18rem;border-color:black;">Nova Senha<label>
                <br>
                {{ form.new_password }}
            </div>
            <br><br>

            <div class="form-group" align="center">
                <label for="exampleInputEmail1" class="form-control" style= "width: 18rem; border-color:black;">Confirmação de nova Senha<label>
                <br>
                {{ form.confirm_password }}
            </div>
            <br><br>
            <br>
            <div class="text-center">
                <button type="submit" class="btn btn-primary" >Mudar Senha</button>
            </div>
        </form>
    </div>
{% endblock %}

todosite/authentication/templates/authentication/sign.html
{% extends "base/base.html" %}
{% block title %}Todo App - Cadastrar{% endblock %}
{% block nav_title %}
    Todo App - Cadastrar
{% endblock %}
{% block body %}
    <br><br>
    <div class="card" style="width: 15rem; margin: 0 auto; border-width:2px; border-color:#0a106e;">
        <form class="form-group" action="/auth/sign-up-success/" method="post">
            {% csrf_token %}
            <br>
            {% if message %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endif %}
            <h5 align="center" class="card-title">Cadastre - se</h5><br>
            <div class="form-group" align="center">
                <label for="exampleInputEmail1" class="form-control" style= "width: 13rem;border-color:black;">Usuário</label>
                {{ form.name }}
                <br>
            </div>
            <div class="form-group" align="center">
                <label for="inputPassword" class="form-control" style=" width: 13rem;border-color:black;">Senha</label>
                {{ form.passwd }}
                <br>
            </div>
            <br>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
        </form>
    </div>
{% endblock %}